name: 'PullRequest to Json'
description: 'プルリクエストの情報をJson化'
inputs:
  pullRequestNumber:
    description: 'PullRequest Number'
    required: true
    default: '1'
runs:
  using: "composite"
  steps:
    - name: PullRequest Number
      run: echo '${{github.event.inputs.pullRequestNumber}}'
    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: |
          console.log(process.env);
          const number = '${{github.event.inputs.pullRequestNumber}}';
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          const pull = github.rest.pulls.get({
            owner,
            repo,
            number
          });

          console.log(pull);

          const result = {
            owner: owner,
            repo: repo,
            number: number
          };
          console.log(result);