name: 'PullRequest to Json'
description: 'プルリクエストの情報をJson化'
inputs:
  pullRequestNumber:
    description: 'PullRequest Number'
runs:
  using: "composite"
  steps:
    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: |
          console.log(inputs);
          const number = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const pull = github.rest.pulls.get({
            owner,
            repo,
            number
          });
          console.log(pull);
          const result = {
            owner: owner,
            repo: repo,
            number: number
          };
          console.log(result);