name: 'PullRequest to Json'
description: 'プルリクエストの情報をJson化'
inputs:
  pullRequestNumber:
    description: 'PullRequest Number'
    required: true
    default: '1'
runs:
  using: "composite"
  steps:
    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: |
          const number = '${{inputs.pullRequestNumber}}';
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          const pull = await github.rest.pulls.get({
            owner: owner,
            repo: repo,
            pull_number: number
          });

          console.log(pull);

          const result = {
            owner: owner,
            repo: repo,
            pull_number: number,
            title: pull.data.title,
            user: pull.data.user.login,
            created_at: pull.data.created_at,
            merged_at: pull.data.merged_at,
            head: pull.data.head.ref,
            base: pull.data.base.ref,
            commits: pull.data.commits,
            additions: pull.data.additions,
            deletions: pull.data.deletions,
            changed_files: pull.data.changed_files
          };
          console.log(result);