name: 'PullRequest to Json'
description: 'プルリクエストの情報をJson化'
inputs:
  pullRequestNumber:
    description: 'PullRequest Number'
    required: true
    default: '1'
runs:
  using: "composite"
  steps:
    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: |
          const number = '${{inputs.pullRequestNumber}}';
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          const pull = await github.rest.pulls.get({
            owner: owner,
            repo: repo,
            pull_number: number
          });

          console.log(pull);

          const result = {
            owner: owner,
            repo: repo,
            number: number
          };
          console.log(result);